### ISSUE TITLE
grid-*-tablet doesn't override max-width

### ISSUE THREAD

**Issue by hidnasio** [OwlyStuff/amazium#109]
I have something like this

```html
<div class="row">
    <div class="grid-8 grid-12-mobile grid-12-tablet">
    </div>
</div>
```

and I would expect

* size 8 in desktop
* size 12 in tablet
* size 12 in mobile

but this [rule](https://github.com/hidnasio/amazium/blob/2cde84d38eae7c6cffdfe19d8a821e92e0e23c9e/scss/_grid.scss#L117)

```css
@media only screen and (min-width:768px) and (max-width:959px) {
    .grid-12-tablet {
        flex-basic:100%;
    }
}
```

doesn't override the max-width of this [rule](https://github.com/hidnasio/amazium/blob/2cde84d38eae7c6cffdfe19d8a821e92e0e23c9e/scss/_grid.scss#L58)

```css
@media (min-width:768px) {
    .grid-8 {
        flex-basis:66.66667%;
        max-width:66.66667%;
    }
}
```

so I'm getting `flex-basis:100%` and `max-width:66.66667%` when `max-width` should be 100%.

I don't know if this is intended or not. If it's bug then I would be happy to do a pull request to fix this.

Thanks!
